const Map<String, Map<String, String>> appStrings = {
  'en': {
    'app_name': 'AgriLink Ethiopia',
    'tagline': 'Fresh · Local · Direct',
    'hero_title': 'Farm-fresh produce, no middlemen',
    'browse_farmers': 'Browse farmers',
    'how_it_works': 'How it works',
    'marketplace': 'Marketplace',
    'farmers': 'Farmers',
    'orders': 'Orders',
    'messages': 'Messages',
    'profile': 'Profile',
    'dashboard': 'Dashboard',
    'add_to_cart': 'Add to cart',
    'place_order': 'Place Order',
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'full_name': 'Full Name',
    'phone': 'Phone',
    'logout': 'Logout',
    'cancel': 'Cancel',
    'save': 'Save',
    'search': 'Search products, farmers...',
    'cart': 'Cart',
    'checkout': 'Checkout',
    'total': 'Total',
    'empty_cart': 'Your cart is empty',
    'no_products': 'No products found',
    'no_farmers': 'No farmers found',
    'no_orders': 'No orders yet',
    'no_messages': 'No messages yet',
  },
  'am': {
    'app_name': 'AgriLink Ethiopia',
    'tagline': 'ትኩስ · አካባቢያዊ · ቀጥታ',
    'hero_title': 'ከእርሻ ቀጥታ ምርቶች፣ ያለ ደላላ',
    'browse_farmers': 'ገበሬዎችን ይመልከቱ',
    'how_it_works': 'እንዴት ይሰራል',
    'marketplace': 'ገበያ',
    'farmers': 'ገበሬዎች',
    'orders': 'ትዕዛዞች',
    'messages': 'መልዕክቶች',
    'profile': 'መገለጫ',
    'dashboard': 'ዳሽቦርድ',
    'add_to_cart': 'ወደ ጋሪ ጨምር',
    'place_order': 'ትዕዛዝ ሰጥ',
    'sign_in': 'ግባ',
    'sign_up': 'ተመዝገብ',
    'email': 'ኢሜይል',
    'password': 'የይለፍ ቃል',
    'full_name': 'ሙሉ ስም',
    'phone': 'ስልክ',
    'logout': 'ውጣ',
    'cancel': 'ሰርዝ',
    'save': 'አስቀምጥ',
    'search': 'ምርቶችን ፣ ገበሬዎችን ይፈልጉ...',
    'cart': 'ጋሪ',
    'checkout': 'ክፍያ',
    'total': 'ጠቅላላ',
    'empty_cart': 'ጋሪዎ ባዶ ነው',
    'no_products': 'ምንም ምርቶች አልተገኙም',
    'no_farmers': 'ምንም ገበሬዎች አልተገኙም',
    'no_orders': 'ምንም ትዕዛዞች የሉም',
    'no_messages': 'ምንም መልዕክቶች የሉም',
  },
  'or': {
    'app_name': 'AgriLink Ethiopia',
    'tagline': 'Dhibee · Naannoo · Kallattiin',
    'hero_title': 'Oomisha qonnaa kallattii, harkaa daldalaa malee',
    'browse_farmers': 'Qonnaan bultootaa ilaali',
    'how_it_works': 'Akkamitti hojjeta',
    'marketplace': 'Gabaa',
    'farmers': 'Qonnaan bultootaa',
    'orders': 'Ajajawwan',
    'messages': 'Ergaawwan',
    'profile': 'Profaayilii',
    'dashboard': 'Daashboordii',
    'add_to_cart': 'Gaarii itti ida\'i',
    'place_order': 'Ajaji',
    'sign_in': 'Seeni',
    'sign_up': 'Galme\'i',
    'email': 'Imeelii',
    'password': 'Jecha darbii',
    'full_name': 'Maqaa guutuu',
    'phone': 'Bilbila',
    'logout': 'Ba\'i',
    'cancel': 'Haqi',
    'save': 'Olkaa\'i',
    'search': 'Oomisha, qonnaan bultoonota barbaadi...',
    'cart': 'Gaarii',
    'checkout': 'Kafaltii',
    'total': 'Waliigala',
    'empty_cart': 'Gaariin kee duwwaa dha',
    'no_products': 'Oomishni hin argamne',
    'no_farmers': 'Qonnaan bultoonni hin argamne',
    'no_orders': 'Ajajni hin jiru',
    'no_messages': 'Ergaan hin jiru',
  },
};

const List<String> ethiopianRegions = [
  'Addis Ababa',
  'Oromia',
  'Amhara',
  'Tigray',
  'SNNPR',
  'Sidama',
  'Somali',
  'Afar',
  'Benishangul-Gumuz',
  'Gambela',
  'Harari',
  'Dire Dawa',
];

const List<String> paymentMethods = [
  'Telebirr',
  'CBE Birr',
  'HelloCash',
  'Bank Transfer',
  'Cash on Delivery',
];

const List<String> productCategories = [
  'Vegetables & Fruits',
  'Grains & Cereals',
  'Dairy & Eggs',
  'Meat & Poultry',
];

const Map<String, String> categoryEmojis = {
  'Vegetables & Fruits': '🥬',
  'Grains & Cereals': '🌾',
  'Dairy & Eggs': '🥛',
  'Meat & Poultry': '🍗',
};

const List<String> productUnits = [
  'kg',
  'gram',
  'piece',
  'litre',
  'quintal',
];
